const arquetipoVantagens = {
    "O Acadêmico": ["Autoridade", "Educação de Elite", "Rede Acadêmica", "Colecionador", "Coleta de Dados", "Especialista", "Estudos de Ocultismo", "Esportista de Elite"],
    "A Agente": ["Infiltrados", "Arrombador", "Analista", "Astuto", "Perito em Explosivos", "Varredura", "Agente de Campo", "Inabalável"],
    "O Amaldiçoado": ["Intuição Mágica", "Vínculo", "Estudos de Ocultismo", "Ímpeto Temerário", "Impiedoso", "Desesperado", "Destino Selado", "Sacrifício Pessoal"],
    "A Arruinada": ["Consciência Ampliada", "Enveredamento", "Insanidade Contagiante", "Intuição Mágica", "Sexto Sentido", "Contatos das Ruas", "Intuitivo", "Destemido"],
    "O Artista": ["Consciência Ampliada", "Encantador de Serpentes", "Inspiração Proibida", "Fascínio", "Notório", "Talento Artístico", "Observador", "Consciência Corporal"],
    "O Atravessador": ["Sexto Sentido", "Língua de Cobra", "Malandragem", "Ás na Manga", "Ataque Furtivo", "Chefão do Crime", "Extorsionista", "Viajado"],
    "O Brinquedo": ["Atração Magnética", "Divino", "Vitimista", "Ataque Furtivo", "Furtividade", "Sangue Frio", "Inabalável", "Indomável"],
    "A Carreirista": ["Amigos Influentes", "Imponente", "Notório", "Rede de Contatos", "Destemido", "Titereiro", "Ambicioso", "Oportunista"],
    "O Cientista": ["Consciência Ampliada", "Gênio", "Implantação de Mensagens", "Cientista", "Inventor", "Paramédico", "Pesquisador Arcano", "Workaholic"],
    "O Criminoso": ["Sexto Sentido", "Malandragem", "Arrombador", "Artista da Fuga", "Algoz", "Briga de Rua", "Líder de Gangue", "Olhar Mortal"],
    "A Descendente": ["Artefato", "Consciência Ampliada", "Poder Interior", "Vínculo", "Amigos Influentes", "Intuitivo", "Biblioteca de Ocultismo", "Vigias"],
    "O Detetive": ["Consciência Ampliada", "Sonhador", "Verborragia", "Interrogador", "Instinto" ,"Sombra", "Sondagem de Grupo", "Investigador Forense"],
    "A Enganadora": ["Impostor", "Sedutor", "Sensualidade", "Ataque Furtivo", "Intuitivo", "Olhar Minucioso", "Manipulador", "Rancor"],
    "A Indagadora": ["Consciência Ampliada", "Obstinado", "Parkour", "Acesso à Dark Net", "Olho Clínico", "Hacker", "Precavido", "Inabalável"],
    "O Nômade": ["Artefato", "Consciência Ampliada", "Contatos das Ruas", "Improvisador", "Piloto", "Atento", "Personificação", "Andarilho"],
    "A Ocultista": ["Consciência Ampliada", "Exorcista", "Intuição Mágica", "Ocultista Amador", "Sonhador", "Ardiloso", "Biblioteca de Ocultismo", "Sede de Conhecimento"],
    "A Profetisa": ["Aura Carismática", "Consciência Ampliada", "Exorcista", "Imposição de Mãos", "Líder de Culto", "Voz da Insanidade", "Bom Samaritano", "Guerreiro Divino"],
    "A Ronin": ["Sexto Sentido", "Mestre das Armas", "Camaleão", "Saída Estratégica", "Rastreador", "Movimentos Ágeis", "Sniper", "Indiferença"],
    "O Veterano": ["Voz da Dor", "Caçador", "Instinto", "Técnicas de Sobrevivência", "Combate Tático", "Perito em Artes Marciais", "Durão", "Tiro Certeiro"],
    "A Vingadora": ["Consciência Ampliada", "Comunicação Animal", "Instinto", "Instinto de Sobrevivência", "Intimidador", "Código de Honra", "Fúria", "Olho por Olho"]
}

const vantagens = {
    "Acesso à Dark Net": {
        nome: "Acesso à Dark Net",
        icon: "fa-user-secret",
        atributo: "Percepção",
        descricao: " Você sabe como acessar e pesquisar no abismo da Dark Net.",
    },
    "Agente de Campo": {
        nome: "Agente de Campo",
        icon: "fa-person-rifle",
        atributo: "Violência",
        descricao: "Você ganha Trunfos quando entra em combate."
    },
    "Algoz": {
        nome: "Algoz",
        icon: "fa-person-harassing",
        atributo: "Violência",
        descricao: "Você pode ameaçar as pessoas a fazerem o que você quer."
    },
    "Ambicioso": {
        nome: "Ambicioso",
        icon: "fa-hands-holding-circle",
        atributo: "-",
        descricao: "Você pode obter +2 em uma rolagem diminuindo -2 de Estabilidade",
    },
    "Amigos Influentes": {
        nome: "Amigos Influentes",
        icon: "fa-handshake-angle",
        atributo: "Carisma",
        descricao: "Você tem amigos com poder e influência.",
    },
    "Analista": {
        nome: "Analista",
        icon: "fa-file-signature",
        atributo: "Razão",
        descricao: "Você é bom em fazer conexões quando você Investigar.",
    },
    "Andarilho": {
        nome: "Andarilho",
        icon: "fa-map-location",
        atributo: "Percepção",
        descricao: "Você sabe coisas sobre os lugares.",
    },
    "Ardiloso": {
        nome: "Ardiloso",
        icon: "fa-children",
        atributo: "Intuição",
        descricao: "Você pode fazer os outros confiarem em você.",
    },
    "Arrombador": {
        nome: "Arrombador",
        icon: "fa-door-open",
        atributo: "Firmeza",
        descricao: "Você é um especialista em arrombamento e invasão.",
    },
    "Artefato": {
        nome: "Artefato",
        icon: "fa-wand-sparkles",
        atributo: "Alma",
        descricao: "Você tem um artefato com poderes místicos.",
    },
    "Artista da Fuga": {
        nome: "Artista da Fuga",
        icon: "fa-person-running",
        atributo: "Firmeza",
        descricao: "Você é um mestre da fuga quando a merda bate no ventilador.",
    },
    "Ás na Manga": {
        nome: "Ás na Manga",
        icon: "fa-lightbulb",
        atributo: "Firmeza",
        descricao: "Você se sai bem de enrascadas.",
    },
    "Astuto": {
        nome: "Astuto",
        icon: "fa-car-on",
        atributo: "Razão",
        descricao: "Você é bom em bolar formas de escapar do perigo.",
    },
    "Ataque Furtivo": {
        nome: "Ataque Furtivo",
        icon: "fa-user-ninja",
        atributo: "Firmeza",
        descricao: "Você é perigoso quando ataca vítimas despreparadas.",
    },
    "Atento": {
        nome: "Atento",
        icon: "fa-pen-clip",
        atributo: "Intuição",
        descricao: "Você percebe quando escondem coisas de você ao Ler uma Pessoa.",
    },
    "Atração Magnética": {
        nome: "Atração Magnética",
        icon: "fa-magnet",
        atributo: "Alma",
        descricao: "Você pode atrair pessoas para você.",
    },
    "Aura Carismática": {
        nome: "Aura Carismática",
        icon: "fa-hand-holding-hand",
        atributo: "Alma",
        descricao: "Você pode forçar as pessoas a confiar em você e buscar a sua companhia.",
    },
    "Autoridade": {
        nome: "Autoridade",
        icon: "fa-graduation-cap",
        atributo: "Carisma",
        descricao: "Você pode usar sua autoridade acadêmica para influenciar os outros.",
    },
    "Biblioteca de Ocultismo": {
        nome: "Biblioteca de Ocultismo",
        icon: "fa-swatchbook",
        atributo: "Razão",
        descricao: "Você tem uma biblioteca sobre o oculto.",
    },
    "Bom Samaritano": {
        nome: "Bom Samaritano",
        icon: "fa-hand-holding-medical",
        atributo: "-",
        descricao: "Ganhe Estabilidade quando você ajudar os outros às suas custas.",
    },
    "Briga de Rua": {
        nome: "Briga de Rua",
        icon: "fa-hand-fist",
        atributo: "Violência",
        descricao: "Você ganha Trunfos em lutas corpo a corpo.",
    },
    "Caçador": {
        nome: "Caçador",
        icon: "fa-crosshairs",
        atributo: "Percepção",
        descricao: "Você é um caçador habilidoso.",
    },
    "Camaleão": {
        nome: "Camaleão",
        icon: "fa-shoe-prints",
        atributo: "Intuição",
        descricao: "Você é ótimo em disfarçar sua aparência e imitar os outros.",
    },
    "Chefão do Crime": {
        nome: "Chefão do Crime",
        icon: "fa-handcuffs",
        atributo: "Firmeza",
        descricao: "Você tem uma gangue de capangas criminosos.",
    },
    "Cientista": {
        nome: "Cientista",
        icon: "fa-flask-vial",
        atributo: "Razão",
        descricao: "Você é bom em Investigar objetos ou entidades.",
    },
    "Código de Honra": {
        nome: "Código de Honra",
        icon: "fa-award",
        atributo: "-",
        descricao: "Ganhe Estabilidade ao assumir riscos ou fazer sacrifícios pelo seu código de honra.",
    },
    "Colecionador": {
        nome: "Colecionador",
        icon: "fa-jar",
        atributo: "Razão",
        descricao: "Você sabe como encontrar itens incomuns ou raros.",
    },
    "Coleta de Dados": {
        nome: "Coleta de Dados",
        icon: "fa-newspaper",
        atributo: "Razão",
        descricao: "Você é um pesquisador habilidoso.",
    },
    "Combate Tático": {
        nome: "Combate Tático",
        icon: "fa-person-military-rifle",
        atributo: "Violência",
        descricao: "Você ganha Trunfos quando luta com aliados ao seu lado.",
    },
    "Comunicação Animal": {
        nome: "Comunicação Animal",
        icon: "fa-paw",
        atributo: "Intuição",
        descricao: "Você pode controlar animais.",
    },
    "Consciência Ampliada": {
        nome: "Consciência Ampliada",
        icon: "fa-eye",
        atributo: "Alma",
        descricao: "Você pode se abrir para ter visões e se comunicar com entidades de outras dimensões.",
    },
    "Consciência Corporal": {
        nome: "Consciência Corporal",
        icon: "fa-person",
        atributo: "Percepção",
        descricao: "Você tem controle excepcional sobre seu corpo.",
    },
    "Contatos das Ruas": {
        nome: "Contatos das Ruas",
        icon: "fa-people-group",
        atributo: "Carisma",
        descricao: "Você tem contatos entre os forasteiros e párias sociais.",
    },
    "Desesperado": {
        nome: "Desesperado",
        icon: "fa-person-praying",
        atributo: "-",
        descricao: "Você recebe +1 em todas as rolagens para avançar frente grandes desafios.",     
    },
    "Destemido": {
        nome: "Destemido",
        icon: "fa-skull",
        atributo: "Percepção",
        descricao: "Você ganha Trunfos quando entra em situações perigosas.",
    },
    "Destino Selado": {
        nome: "Destino Selado",
        icon: "fa-hourglass-half",
        atributo: "-",
        descricao: "Você pode usar seu Tempo para estabilizar feridas.",
    },
    "Divino": {
        nome: "Divino",
        icon: "fa-cross",
        atributo: "Alma",
        descricao: "Você pode fazer monstros te obedecer temporariamente.",
    },
    "Durão": {
        nome: "Durão",
        icon: "fa-user-injured",
        atributo: "-",
        descricao: "Você recebe +1 constante para Suportar Lesão.",
    },
    "Educação de Elite": {
        nome: "Educação de Elite",
        icon: "fa-user-graduate",
        atributo: "Carisma",
        descricao: "Você tem contatos na elite social do mundo.",
    },
    "Encantador de Serpentes": {
        nome: "Encantador de Serpentes",
        icon: "fa-staff-snake",
        atributo: "Alma",
        descricao: "Você pode encantar criaturas inteligentes e monstruosas com sua arte.",
    },
    "Enveredamento": {
        nome: "Enveredamento",
        icon: "fa-people-pulling",
        atributo: "Alma",
        descricao: "Você pode deixar sua loucura conduzi-lo por atalhos na cidade.",
    },
    "Especialista": {
        nome: "Especialista",
        icon: "fa-clipboard-question",
        atributo: "Razão",
        descricao: "Você pode fazer uma pergunta adicional e perguntar o que quiser quando Investigar coisas em suas áreas de conhecimento.",
    },
    "Esportista de Elite": {
        nome: "Esportista de Elite",
        icon: "fa-baseball-bat-ball",
        atributo: "-",
        descricao: "Você competiu profissionalmente em um esporte.",
    },
    "Estudos de Ocultismo": {
        nome: "Estudos de Ocultismo",
        icon: "fa-ghost",
        atributo: "Razão",
        descricao: "Você sabe coisas sobre o oculto.",
    },
    "Exorcista": {
        nome: "Exorcista",
        icon: "fa-hands-praying",
        atributo: "Alma",
        descricao: "Você pode fazer rituais para banir espíritos e demônios.",
    },
    "Extorsionista": {
        nome: "Extorsionista",
        icon: "fa-person-falling",
        atributo: "Intuição",
        descricao: "Você pode ver fraquezas dos outros quando Ler uma Pessoa.",
    },
    "Fascínio": {
        nome: "Fascínio",
        icon: "fa-palette",
        atributo: "Carisma",
        descricao: "Você pode usar a sua arte para seduzir um PNJ.",
    },
    "Fúria": {
        nome: "Fúria",
        icon: "fa-fire-flame-curved",
        atributo: "-",
        descricao: "Entre em fúria para ganhar Trunfos em combate.",
    },
    "Furtividade": {
        nome: "Furtividade",
        icon: "fa-eye-slash",
        atributo: "Firmeza",
        descricao: "Você pode evitar a detecção ao se esconder ou se esgueirar.",
    },
    "Gênio": {
        nome: "Gênio",
        icon: "fa-brain",
        atributo: "Alma",
        descricao: "Você ganha Trunfos em situações de risco de vida.",
    },
    "Guerreiro Divino": {
        nome: "Guerreiro Divino",
        icon: "fa-chess-rook",
        atributo: "-",
        descricao: "Você fica mais forte quando luta contra os inimigos da sua divindade ou protege um objeto sagrado.",
    },
    "Hacker": {
        nome: "Hacker",
        icon: "fa-laptop-file",
        atributo: "Razão",
        descricao: "Você é especialista em invadir redes.",
    },
    "Ímpeto Temerário": {
        nome: "Ímpeto Temerário",
        icon: "fa-person-falling-burst",
        atributo: "Violência",
        descricao: "Você ganha Trunfos quando luta sem se importar com sua segurança pessoal.",
    },
    "Impiedoso": {
        nome: "Impiedoso",
        icon: "fa-person-digging",
        atributo: "Violência",
        descricao: "Você ganha Trunfos quando você sacrifica os outros para se salvar.",
    },
    "Implantação de Mensagens": {
        nome: "Implantação de Mensagens",
        icon: "fa-hands-holding-child",
        atributo: "Alma",
        descricao: "Você pode ter poder sobre os humanos fazendo experimentos com eles.",
    },
    "Imponente": {
        nome: "Imponente",
        icon: "fa-person-military-pointing",
        atributo: "Carisma",
        descricao: "Você pode inspirar admiração e obediência nos outros.",
    },
    "Imposição de Mãos": {
        nome: "Imposição de Mãos",
        icon: "fa-kit-medical",
        atributo: "Alma",
        descricao: "Você pode curar alguém sacrificando a si mesmo ou uma vítima.",
    },
    "Impostor": {
        nome: "Impostor",
        icon: "fa-hand-holding-heart",
        atributo: "Carisma",
        descricao: "Você tem vários relacionamentos românticos para usar a seu favor.",
    },
    "Improvisador": {
        nome: "Improvisador",
        icon: "fa-person-walking-dashed-line-arrow-right",
        atributo: "Firmeza",
        descricao: "Você é bom em dar um jeito de sair de situações perigosas.",
    },
    "Inabalável": {
        nome: "Inabalável",
        icon: "fa-shield-halved",
        atributo: "-",
        descricao: "Sempre que você reduz Estabilidade, você sempre perde 1 nível a menos que o normal.",
    },
    "Indiferença": {
        nome: "Indiferença",
        icon: "fa-person-drowning",
        atributo: "-",
        descricao: "Você pode suprimir os efeitos de um (10-14) com Manter o Controle.",
    },
    "Indomável": {
        nome: "Indomável",
        icon: "fa-person-rays",
        atributo: "-",
        descricao: "Você não sofre penalidades de ferimentos nas rolagens.",
    },
    "Infiltrados": {
        nome: "Infiltrados",
        icon: "fa-people-line",
        atributo: "Carisma",
        descricao: "Você tem um número de infiltrados para usar quando necessário.",
    },
    "Insanidade Contagiante": {
        nome: "Insanidade Contagiante",
        icon: "fa-arrows-down-to-people",
        atributo: "Alma",
        descricao: "Você pode infectar outras pessoas com insanidade temporária.",
    },
    "Inspiração Proibida": {
        nome: "Inspiração Proibida",
        icon: "fa-paintbrush",
        atributo: "Alma",
        descricao: "Você pode usar sua arte para ter visões e atrair criaturas até você.",
    },
    "Instinto": {
        nome: "Instinto",
        icon: "fa-file-invoice",
        atributo: "Percepção",
        descricao: "Você recebe +2 em suas perguntas quando você Observar uma Situação.",
    },
    "Instinto de Sobrevivência": {
        nome: "Instinto de Sobrevivência",
        icon: "fa-dumbbell",
        atributo: "Violência",
        descricao: "Você fica mais violento quando está ferido.",
    },
    "Interrogador": {
        nome: "Interrogador",
        icon: "fa-street-view",
        atributo: "Intuição",
        descricao: "Você é especialista em pegar as mentiras quando Ler uma Pessoa.",
    },
    "Intimidador": {
        nome: "Intimidador",
        icon: "fa-people-arrows",
        atributo: "Violência",
        descricao: "Você pode assustar os outros para cederem.",
    },
    "Intuição Mágica": {
        nome: "Intuição Mágica",
        icon: "fa-hand-sparkles",
        atributo: "Alma",
        descricao: "Você pode perceber as auras kirlianas e sentir a presença da magia.",
    },
    "Intuitivo": {
        nome: "Intuitivo",
        icon: "fa-person-circle-question",
        atributo: "Intuição",
        descricao: "Você pode fazer uma pergunta adicional quando tiver sucesso em Ler uma Pessoa.",
    },
    "Inventor": {
        nome: "Inventor",
        icon: "fa-hammer",
        atributo: "Razão",
        descricao: "Você pode criar e reparar coisas.",
    },
    "Investigador Forense": {
        nome: "Investigador Forense",
        icon: "fa-magnifying-glass",
        atributo: "Razão",
        descricao: "Você é um especialista em encontrar pistas em cenas de crime.",
    },
    "Líder de Culto": {
        nome: "Líder de Culto",
        icon: "fa-church",
        atributo: "Alma",
        descricao: "Você pode realizar rituais com seus seguidores.",
    },
    "Líder de Gangue": {
        nome: "Líder de Gangue",
        icon: "fa-user-group",
        atributo: "Violência",
        descricao: "Você tem uma gangue de criminosos.",
    },
    "Língua de Cobra": {
        nome: "Língua de Cobra",
        icon: "fa-users-rays",
        atributo: "Carisma",
        descricao: "Você pode manipular os outros para confiarem em você",
    },
    "Malandragem": {
        nome: "Malandragem",
        icon: "fa-people-robbery",
        atributo: "Carisma",
        descricao: "Você tem contatos no submundo do crime.",
    },
    "Manipulador": {
        nome: "Manipulador",
        icon: "fa-mask",
        atributo: "-",
        descricao: "Você pode usar seus favores prévios e segredos das pessoas contra elas.",
    },
    "Mestre das Armas": {
        nome: "Mestre das Armas",
        icon: "fa-gun",
        atributo: "Firmeza",
        descricao: "Você é um mestre em combate armado ou tiroteio.",
    },
    "Movimentos Ágeis": {
        nome: "Movimentos Ágeis",
        icon: "fa-person-skating",
        atributo: "Violência",
        descricao: "Você ganha Trunfos quando você se move rápido em combate.",
    },
    "Notório": {
        nome: "Notório",
        icon: "fa-people-carry-box",
        atributo: "Carisma",
        descricao: "Você pode usar sua fama para influenciar as pessoas.",
    },
    "Observador": {
        nome: "Observador",
        icon: "fa-binoculars",
        atributo: "Intuição",
        descricao: "Você é bom em julgar o caráter de alguém.",
    },
    "Obstinado": {
        nome: "Obstinado",
        icon: "fa-triangle-exclamation",
        atributo: "Alma",
        descricao: "Você pode se esforçar para superar ameaças e ganhar Trunfos.",
    },
    "Ocultista Amador": {
        nome: "Ocultista Amador",
        icon: "fa-scroll",
        atributo: "Alma",
        descricao: "Você pode realizar rituais através de instruções escritas.",
    },
    "Olhar Minucioso": {
        nome: "Olhar Minucioso",
        icon: "fa-shirt",
        atributo: "Percepção",
        descricao: "Você é bom em reparar nos detalhes numa pessoa.",
    },
    "Olhar Mortal": {
        nome: "Olhar Mortal",
        icon: "fa-skull-crossbones",
        atributo: "Violência",
        descricao: "Você pode congelar PNJ com o seu olhar.",
    },
    "Olho Clínico": {
        nome: "Olho Clínico",
        icon: "fa-square-person-confined",
        atributo: "Percepção",
        descricao: "Você é habilidoso em identificar as forças e fraquezas dos inimigos.",
    },
    "Olho por Olho": {
        nome: "Olho por Olho",
        icon: "fa-syringe",
        atributo: "-",
        descricao: "Você recebe +2 constante em todas as rolagens contra alguém que ferir você.",
    },
    "Oportunista": {
        nome: "Oportunista",
        icon: "fa-handshake-simple-slash",
        atributo: "-",
        descricao: "Ganhe Estabilidade quando você sacrificar alguém para avançar seus próprios objetivos.",
    },
    "Paramédico": {
        nome: "Paramédico",
        icon: "fa-user-nurse",
        atributo: "Razão",
        descricao: "Você é treinado em estabilizar ferimentos.",
    },
    "Parkour": {
        nome: "Parkour",
        icon: "fa-person-walking",
        atributo: "Firmeza",
        descricao: "Você é hábil em correr, escalar e pular.",
    },
    "Perito em Artes Marciais": {
        nome: "Perito em Artes Marciais",
        icon: "fa-person-walking-with-cane",
        atributo: "Violência",
        descricao: "Você ganha Trunfos em lutas corpo a corpo.",
    },
    "Perito em Explosivos": {
        nome: "Perito em Explosivos",
        icon: "fa-bomb",
        atributo: "Razão",
        descricao: "Você pode construir e desarmar bombas.",
    },
    "Personificação": {
        nome: "Personificação",
        icon: "fa-user-tie",
        atributo: "Intuição",
        descricao: "Você é um mestre em se misturar.",
    },
    "Pesquisador Arcano": {
        nome: "Pesquisador Arcano",
        icon: "fa-hat-wizard",
        atributo: "-",
        descricao: "Você sabe coisas sobre planos alternativos de existência e criaturas de outras dimensões.",
    },
    "Piloto": {
        nome: "Piloto",
        icon: "fa-car-burst",
        atributo: "Firmeza",
        descricao: "Você é um profissional treinado em operar veículos motorizados.",
    },
    "Poder Interior": {
        nome: "Poder Interior",
        icon: "fa-hands-holding-circle",
        atributo: "Alma",
        descricao: "Você nutre um poder perigoso e incontrolável.",
    },
    "Precavido": {
        nome: "Precavido",
        icon: "fa-globe",
        atributo: "Razão",
        descricao: "Você é bom em pesquisar lugares.",
    },
    "Rancor": {
        nome: "Rancor",
        icon: "fa-hand-point-up",
        atributo: "-",
        descricao: "Você recebe +1 constante para se vingar quando alguém estraga seus planos.",
    },
    "Rastreador": {
        nome: "Rastreador",
        icon: "fa-id-card",
        atributo: "Razão",
        descricao: "Você é bom em conseguir informações sobre as pessoas.",
    },
    "Rede Acadêmica": {
        nome: "Rede Acadêmica",
        icon: "fa-building-columns",
        atributo: "Carisma",
        descricao: "Você tem contato com universidades por todo o mundo.",
    },
    "Rede de Contatos": {
        nome: "Rede de Contatos",
        icon: "fa-phone-volume",
        atributo: "Carisma",
        descricao: "Você pode conseguir informações sobre as pessoas.",
    },
    "Sacrifício Pessoal": {
        nome: "Sacrifício Pessoal",
        icon: "fa-stopwatch",
        atributo: "-",
        descricao: "Você pode usar seu Tempo para rerrolar os dados.",
    },
    "Saída Estratégica": {
        nome: "Saída Estratégica",
        icon: "fa-crow",
        atributo: "Percepção",
        descricao: "Você é um especialista em esconder os rastros das suas mortes.",
    },
    "Sangue Frio": {
        nome: "Sangue Frio",
        icon: "fa-spa",
        atributo: "Firmeza",
        descricao: "Você pode usar sua calma e frieza em meio à violência e ao caos.",
    },
    "Sede de Conhecimento": {
        nome: "Sede de Conhecimento",
        icon: "fa-book-open-reader",
        atributo: "-",
        descricao: "Você ganha Estabilidade quando aprende sobre outras dimensões e entidades sobrenaturais.",
    },
    "Sedutor": {
        nome: "Sedutor",
        icon: "fa-heart-crack",
        atributo: "Carisma",
        descricao: "Você pode fazer as pessoas se apaixonarem por você.",
    },
    "Sensualidade": {
        nome: "Sensualidade",
        icon: "fa-person-breastfeeding",
        atributo: "Carisma",
        descricao: "Você pode usar sua atratividade para influenciar os outros.",
    },
    "Sexto Sentido": {
        nome: "Sexto Sentido",
        icon: "fa-biohazard",
        atributo: "Alma",
        descricao: "Você pode sentir o perigo e o caminho certo à sua frente.",
    },
    "Sniper": {
        nome: "Sniper",
        icon: "fa-location-crosshairs",
        atributo: "Violência",
        descricao: "Você é um mestre em atirar contra alvos distantes.",
    },
    "Sombra": {
        nome: "Sombra",
        icon: "fa-fingerprint",
        atributo: "Percepção",
        descricao: "Você é habilidoso em seguir pessoas e despistar perseguidores.",
    },
    "Sondagem de Grupo": {
        nome: "Sondagem de Grupo",
        icon: "fa-ear-listen",
        atributo: "Percepção",
        descricao: "Você é um mestre em escutar discretamente informações de grupos de pessoas.",
    },
    "Sonhador": {
        nome: "Sonhador",
        icon: "fa-bed",
        atributo: "Alma",
        descricao: "Você pode usar sonhos para conhecer pessoas ou vivenciar eventos passados.",
    },
    "Talento Artístico": {
        nome: "Talento Artístico",
        icon: "fa-masks-theater",
        atributo: "Carisma",
        descricao: "Seu trabalho artístico tem grande efeito sobre o público.",
    },
    "Técnicas de Sobrevivência": {
        nome: "Técnicas de Sobrevivência",
        icon: "fa-mountain-sun",
        atributo: "Percepção",
        descricao: "Você é treinado em sobreviver na natureza.",
    },
    "Tiro Certeiro": {
        nome: "Tiro Certeiro",
        icon: "fa-bullseye",
        atributo: "-",
        descricao: "Qualquer Dano com armas de fogo tem +1 de Dano.",
    },
    "Titereiro": {
        nome: "Titereiro",
        icon: "fa-users",
        atributo: "Razão",
        descricao: "Você é bom em executar planos usando outras pessoas como peões.",
    },
    "Varredura": {
        nome: "Varredura",
        icon: "fa-microchip",
        atributo: "Razão",
        descricao: "Você tem redes de inteligência para rastrear coisas ou pessoas.",
    },
    "Verborragia": {
        nome: "Verborragia",
        icon: "fa-comments",
        atributo: "Firmeza",
        descricao: "Você é bom em distrair PNJs com conversa fiada.",
    },
    "Viajado": {
        nome: "Viajado",
        icon: "fa-person-walking-luggage",
        atributo: "-",
        descricao: "Estabeleça fatos e relações quando chegar a novos locais na história.",
    },
    "Vigias": {
        nome: "Vigias",
        icon: "fa-user-shield",
        atributo: "-",
        descricao: "Você é vigiado e protegido por um grupo de pessoas misteriosas.",
    },
    "Vínculo": {
        nome: "Vínculo",
        icon: "fa-link",
        atributo: "Alma",
        descricao: "Você pode usar poderes de uma entidade extradimensional.",
    },
    "Vitimista": {
        nome: "Vitimista",
        icon: "fa-children",
        atributo: "Carisma",
        descricao: "Você consegue parecer indefeso e fazer com que as pessoas cuidem de você.",
    },
    "Voz da Dor": {
        nome: "Voz da Dor",
        icon: "fa-droplet",
        atributo: "Alma",
        descricao: "Você aprendeu como lutar melhor contra seus inimigos quando eles ferem você.",
    },
    "Voz da Insanidade": {
        nome: "Voz da Insanidade",
        icon: "fa-users-slash",
        atributo: "Alma",
        descricao: "Você pode manipular grupos de pessoas.",
    },
    "Workaholic": {
        nome: "Workaholic",
        icon: "fa-briefcase",
        atributo: "-",
        descricao: "Ganhe Estabilidade quando você cria coisas ou realiza experimentos.",
    }
}
